output   = "models"
wipe     = true
no-tests = true
no-hooks = true

[psql]
  dbname = "testdb"
  host   = "localhost"
  port   = 5432
  user   = "testuser"
  pass   = "testpass"
  sslmode   = "disable"
